All Team Headshots Added
unc-pmclub/main-website pull request #6
Opened 2024-02-29 17:37 UTC by jennifer566

2024-03-04 00:04 UTC, bcscc commented
Hey Jennifer, the headshots look great! Just one thing, could you remove the api-key in the firebase.config.js file? Just leave it as "apiKey: import.meta.env.VITE_FIREBASE_API_KEY", this way we won't expose the actual key to visitors of the site for security purposes, thanks!

Once that change is made, I can approve it!

2024-03-04 00:05 UTC, bcscc requested changes
Hey Jennifer, the headshots look great! Just one thing, could you remove the api-key in the firebase.config.js file? Just leave it as "apiKey: import.meta.env.VITE_FIREBASE_API_KEY", this way we won't expose the actual key to visitors of the site for security purposes, thanks!

Once that change is made, I can approve it!

2024-03-04 14:27 UTC, jennifer566 commented
Thank you for catching that issue. I just committed the change to remove the api key!

2024-03-26 00:52 UTC, bcscc approved these changes

2024-03-26 00:56 UTC, merged